# Generated by Django 4.2.7 on 2023-11-14 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Generator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('gen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='generator.generator')),
            ],
        ),
    ]
